import { ElementType } from '../types';

type AppLanguage = 'en' | 'zh';

type AttributeTheme = {
  label: string;
  labelEn: string;
  shortLabel: string;
  shortLabelEn: string;
  color: string;
  glow: string;
  textColor: string;
  selectorBg: string;
  selectorBorder: string;
  cardBackground: string;
  boxGradient: string;
  footerGradient: string;
  themeTextColor: string;
  themeSubTextColor: string;
};

const ATTRIBUTE_THEMES: Record<ElementType, AttributeTheme> = {
  [ElementType.Grass]: {
    label: '发霉草',
    labelEn: 'Mold Grass',
    shortLabel: '霉草',
    shortLabelEn: 'Mold',
    color: '#5F7D4A',
    glow: 'rgba(95, 125, 74, 0.62)',
    textColor: '#f3f7ed',
    selectorBg: '#4E6A3E',
    selectorBorder: '#7FA35A',
    cardBackground: 'bg-gradient-to-br from-[#5F7D4A] via-[#496338] to-[#2B3A21]',
    boxGradient: 'bg-gradient-to-b from-[#5F7D4A]/90 to-[#3B532A]/90',
    footerGradient: 'bg-gradient-to-t from-[#425C32] to-transparent',
    themeTextColor: 'text-white',
    themeSubTextColor: 'text-lime-100',
  },
  [ElementType.Fire]: {
    label: '爆辣',
    labelEn: 'Blaze Spice',
    shortLabel: '爆辣',
    shortLabelEn: 'Spice',
    color: '#D84A1B',
    glow: 'rgba(216, 74, 27, 0.68)',
    textColor: '#fff1ea',
    selectorBg: '#B73E16',
    selectorBorder: '#F08A5D',
    cardBackground: 'bg-gradient-to-br from-[#D84A1B] via-[#9F2D12] to-[#5F140B]',
    boxGradient: 'bg-gradient-to-b from-[#D84A1B]/90 to-[#922E13]/90',
    footerGradient: 'bg-gradient-to-t from-[#A03216] to-transparent',
    themeTextColor: 'text-white',
    themeSubTextColor: 'text-orange-100',
  },
  [ElementType.Water]: {
    label: '霉水',
    labelEn: 'Rot Water',
    shortLabel: '霉水',
    shortLabelEn: 'Rot',
    color: '#3E6B73',
    glow: 'rgba(62, 107, 115, 0.6)',
    textColor: '#eaf6f8',
    selectorBg: '#355D64',
    selectorBorder: '#68A7B3',
    cardBackground: 'bg-gradient-to-br from-[#3E6B73] via-[#2E4F56] to-[#162C31]',
    boxGradient: 'bg-gradient-to-b from-[#3E6B73]/90 to-[#27464C]/90',
    footerGradient: 'bg-gradient-to-t from-[#26474E] to-transparent',
    themeTextColor: 'text-white',
    themeSubTextColor: 'text-cyan-100',
  },
  [ElementType.Lightning]: {
    label: '神经电',
    labelEn: 'Nerve Shock',
    shortLabel: '神电',
    shortLabelEn: 'Shock',
    color: '#E7D73A',
    glow: 'rgba(231, 215, 58, 0.7)',
    textColor: '#261f00',
    selectorBg: '#D2BF17',
    selectorBorder: '#F6EB79',
    cardBackground: 'bg-gradient-to-br from-[#E7D73A] via-[#B59E16] to-[#5E4F08]',
    boxGradient: 'bg-gradient-to-b from-[#E7D73A]/90 to-[#C4A813]/90',
    footerGradient: 'bg-gradient-to-t from-[#B59E16] to-transparent',
    themeTextColor: 'text-black',
    themeSubTextColor: 'text-yellow-950',
  },
  [ElementType.Psychic]: {
    label: '痴线波',
    labelEn: 'Mad Wave',
    shortLabel: '痴波',
    shortLabelEn: 'Mad',
    color: '#A34DB3',
    glow: 'rgba(163, 77, 179, 0.68)',
    textColor: '#fbf0ff',
    selectorBg: '#8C3C9B',
    selectorBorder: '#D49DE0',
    cardBackground: 'bg-gradient-to-br from-[#A34DB3] via-[#743580] to-[#391943]',
    boxGradient: 'bg-gradient-to-b from-[#A34DB3]/90 to-[#6F2D7A]/90',
    footerGradient: 'bg-gradient-to-t from-[#6A2B74] to-transparent',
    themeTextColor: 'text-white',
    themeSubTextColor: 'text-fuchsia-100',
  },
  [ElementType.Fighting]: {
    label: '街口霸气',
    labelEn: 'Street Swagger',
    shortLabel: '霸气',
    shortLabelEn: 'Swagger',
    color: '#B5482E',
    glow: 'rgba(181, 72, 46, 0.68)',
    textColor: '#fff0eb',
    selectorBg: '#9F3B26',
    selectorBorder: '#E08A63',
    cardBackground: 'bg-gradient-to-br from-[#B5482E] via-[#7C2F1D] to-[#40170F]',
    boxGradient: 'bg-gradient-to-b from-[#B5482E]/90 to-[#7E311F]/90',
    footerGradient: 'bg-gradient-to-t from-[#7A2F1E] to-transparent',
    themeTextColor: 'text-white',
    themeSubTextColor: 'text-orange-100',
  },
  [ElementType.Darkness]: {
    label: '死黑',
    labelEn: 'Dead Black',
    shortLabel: '死黑',
    shortLabelEn: 'Black',
    color: '#2A2A2A',
    glow: 'rgba(42, 42, 42, 0.75)',
    textColor: '#f5f5f5',
    selectorBg: '#232323',
    selectorBorder: '#5A5A5A',
    cardBackground: 'bg-gradient-to-br from-[#2E2E2E] via-[#161616] to-[#020202]',
    boxGradient: 'bg-gradient-to-b from-[#2E2E2E]/92 to-black/92',
    footerGradient: 'bg-gradient-to-t from-[#111111] to-transparent',
    themeTextColor: 'text-white',
    themeSubTextColor: 'text-zinc-300',
  },
  [ElementType.Metal]: {
    label: '烂铁',
    labelEn: 'Scrap Metal',
    shortLabel: '烂铁',
    shortLabelEn: 'Scrap',
    color: '#7A4B43',
    glow: 'rgba(122, 75, 67, 0.68)',
    textColor: '#fff0ed',
    selectorBg: '#694038',
    selectorBorder: '#B57D72',
    cardBackground: 'bg-gradient-to-br from-[#7A4B43] via-[#5B3732] to-[#281918]',
    boxGradient: 'bg-gradient-to-b from-[#7A4B43]/90 to-[#54322D]/90',
    footerGradient: 'bg-gradient-to-t from-[#4E2F2B] to-transparent',
    themeTextColor: 'text-white',
    themeSubTextColor: 'text-rose-100',
  },
  [ElementType.Dragon]: {
    label: '反骨龙',
    labelEn: 'Rebel Dragon',
    shortLabel: '反龙',
    shortLabelEn: 'Rebel',
    color: '#7C3F52',
    glow: 'rgba(124, 63, 82, 0.72)',
    textColor: '#fff1f5',
    selectorBg: '#6C3448',
    selectorBorder: '#C07A93',
    cardBackground: 'bg-gradient-to-br from-[#7C3F52] via-[#592B3A] to-[#28131B]',
    boxGradient: 'bg-gradient-to-b from-[#7C3F52]/92 to-[#552735]/92',
    footerGradient: 'bg-gradient-to-t from-[#542534] to-transparent',
    themeTextColor: 'text-white',
    themeSubTextColor: 'text-rose-100',
  },
  [ElementType.Fairy]: {
    label: '花哩碌',
    labelEn: 'Extra Sparkle',
    shortLabel: '花碌',
    shortLabelEn: 'Sparkle',
    color: '#C46A8B',
    glow: 'rgba(196, 106, 139, 0.68)',
    textColor: '#fff6fa',
    selectorBg: '#AD5877',
    selectorBorder: '#F0A7C0',
    cardBackground: 'bg-gradient-to-br from-[#C46A8B] via-[#8F4964] to-[#492333]',
    boxGradient: 'bg-gradient-to-b from-[#C46A8B]/90 to-[#8B4A63]/90',
    footerGradient: 'bg-gradient-to-t from-[#89455F] to-transparent',
    themeTextColor: 'text-white',
    themeSubTextColor: 'text-pink-100',
  },
  [ElementType.Colorless]: {
    label: '求其',
    labelEn: 'Whatever',
    shortLabel: '求其',
    shortLabelEn: 'Whatever',
    color: '#8B8B8B',
    glow: 'rgba(139, 139, 139, 0.55)',
    textColor: '#fafafa',
    selectorBg: '#707070',
    selectorBorder: '#C4C4C4',
    cardBackground: 'bg-gradient-to-br from-[#A3A3A3] via-[#848484] to-[#5F5F5F]',
    boxGradient: 'bg-gradient-to-b from-[#C9C9C9]/88 to-[#A5A5A5]/88',
    footerGradient: 'bg-gradient-to-t from-[#9A9A9A] to-transparent',
    themeTextColor: 'text-black',
    themeSubTextColor: 'text-zinc-700',
  },
  [ElementType.Ice]: {
    label: '冷亲',
    labelEn: 'Cold Snap',
    shortLabel: '冷亲',
    shortLabelEn: 'Cold',
    color: '#6FB7C8',
    glow: 'rgba(111, 183, 200, 0.65)',
    textColor: '#effcff',
    selectorBg: '#519CAE',
    selectorBorder: '#A8E8F6',
    cardBackground: 'bg-gradient-to-br from-[#6FB7C8] via-[#448A9A] to-[#1B4250]',
    boxGradient: 'bg-gradient-to-b from-[#6FB7C8]/90 to-[#448A9A]/90',
    footerGradient: 'bg-gradient-to-t from-[#448A9A] to-transparent',
    themeTextColor: 'text-white',
    themeSubTextColor: 'text-cyan-100',
  },
  [ElementType.Poison]: {
    label: '阴毒',
    labelEn: 'Petty Venom',
    shortLabel: '阴毒',
    shortLabelEn: 'Venom',
    color: '#8D3B6B',
    glow: 'rgba(141, 59, 107, 0.68)',
    textColor: '#fff1fb',
    selectorBg: '#742C55',
    selectorBorder: '#D97DB1',
    cardBackground: 'bg-gradient-to-br from-[#8D3B6B] via-[#5C2142] to-[#260B1B]',
    boxGradient: 'bg-gradient-to-b from-[#8D3B6B]/92 to-[#5E2144]/92',
    footerGradient: 'bg-gradient-to-t from-[#551D3D] to-transparent',
    themeTextColor: 'text-white',
    themeSubTextColor: 'text-fuchsia-100',
  },
  [ElementType.Ground]: {
    label: '烂泥',
    labelEn: 'Mud Mess',
    shortLabel: '烂泥',
    shortLabelEn: 'Mud',
    color: '#6B523A',
    glow: 'rgba(107, 82, 58, 0.66)',
    textColor: '#fff4eb',
    selectorBg: '#5B4430',
    selectorBorder: '#B79162',
    cardBackground: 'bg-gradient-to-br from-[#6B523A] via-[#4C3928] to-[#241A11]',
    boxGradient: 'bg-gradient-to-b from-[#6B523A]/92 to-[#493725]/92',
    footerGradient: 'bg-gradient-to-t from-[#483422] to-transparent',
    themeTextColor: 'text-white',
    themeSubTextColor: 'text-amber-100',
  },
  [ElementType.Flying]: {
    label: '走佬风',
    labelEn: 'Runaway Wind',
    shortLabel: '走风',
    shortLabelEn: 'Runwind',
    color: '#6A7C86',
    glow: 'rgba(106, 124, 134, 0.64)',
    textColor: '#f3f8fb',
    selectorBg: '#55666F',
    selectorBorder: '#A1B8C3',
    cardBackground: 'bg-gradient-to-br from-[#6A7C86] via-[#4A5A63] to-[#1E282D]',
    boxGradient: 'bg-gradient-to-b from-[#6A7C86]/90 to-[#495961]/90',
    footerGradient: 'bg-gradient-to-t from-[#43535B] to-transparent',
    themeTextColor: 'text-white',
    themeSubTextColor: 'text-slate-100',
  },
  [ElementType.Bug]: {
    label: '夜光虫',
    labelEn: 'Glow Bug',
    shortLabel: '夜虫',
    shortLabelEn: 'Glowbug',
    color: '#6FD36A',
    glow: 'rgba(111, 211, 106, 0.68)',
    textColor: '#f3fff2',
    selectorBg: '#56B854',
    selectorBorder: '#B5F4A5',
    cardBackground: 'bg-gradient-to-br from-[#6FD36A] via-[#3F9040] to-[#173D1B]',
    boxGradient: 'bg-gradient-to-b from-[#6FD36A]/90 to-[#3F9040]/90',
    footerGradient: 'bg-gradient-to-t from-[#3B863D] to-transparent',
    themeTextColor: 'text-black',
    themeSubTextColor: 'text-lime-950',
  },
  [ElementType.Rock]: {
    label: '烂石',
    labelEn: 'Trash Rock',
    shortLabel: '烂石',
    shortLabelEn: 'Rock',
    color: '#7D7063',
    glow: 'rgba(125, 112, 99, 0.66)',
    textColor: '#fcf7f2',
    selectorBg: '#675A4E',
    selectorBorder: '#B7A89C',
    cardBackground: 'bg-gradient-to-br from-[#7D7063] via-[#5B5047] to-[#2A241F]',
    boxGradient: 'bg-gradient-to-b from-[#7D7063]/92 to-[#5C5047]/92',
    footerGradient: 'bg-gradient-to-t from-[#534940] to-transparent',
    themeTextColor: 'text-white',
    themeSubTextColor: 'text-stone-100',
  },
  [ElementType.Ghost]: {
    label: '阴气',
    labelEn: 'Spook Fog',
    shortLabel: '阴气',
    shortLabelEn: 'Spook',
    color: '#5A4B6E',
    glow: 'rgba(90, 75, 110, 0.7)',
    textColor: '#f6f2ff',
    selectorBg: '#4A3C5C',
    selectorBorder: '#9C8BC1',
    cardBackground: 'bg-gradient-to-br from-[#5A4B6E] via-[#3C314C] to-[#18121F]',
    boxGradient: 'bg-gradient-to-b from-[#5A4B6E]/92 to-[#3B304A]/92',
    footerGradient: 'bg-gradient-to-t from-[#392E46] to-transparent',
    themeTextColor: 'text-white',
    themeSubTextColor: 'text-violet-100',
  },
};

export const getAttributeTheme = (type: ElementType): AttributeTheme =>
  ATTRIBUTE_THEMES[type] || ATTRIBUTE_THEMES[ElementType.Colorless];

export const getAttributeLabel = (type: ElementType | string | undefined, language: AppLanguage = 'zh'): string => {
  if (!type) return '';
  const theme = getAttributeTheme(type as ElementType);
  return language === 'en' ? theme.labelEn : theme.label;
};

export const getAttributeShortLabel = (type: ElementType | string | undefined, language: AppLanguage = 'zh'): string => {
  if (!type) return '';
  const theme = getAttributeTheme(type as ElementType);
  return language === 'en' ? theme.shortLabelEn : theme.shortLabel;
};
